config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/vinhos')
  resources :harmonizacoes
  resources :pratos
  resources :usuarios
  resources :vinhos

end

app/models/vinho.rb
class Vinho < ActiveRecord::Base
	mount_uploader :foto, PictureUploader
        
end

app/controllers/vinhos_controller.rb
class VinhosController < ApplicationController
  before_action :set_vinho, only: [:show, :edit, :update, :destroy]

  # GET /vinhos
  # GET /vinhos.json
  def index
    #@vinhos = Vinho.all
    @vinhos = Vinho.all.page(params['page']).per(15)
  end

  # GET /vinhos/1
  # GET /vinhos/1.json
  def show
  end

  # GET /vinhos/new
  def new
    @vinho = Vinho.new
  end

  # GET /vinhos/1/edit
  def edit
  end

  # POST /vinhos
  # POST /vinhos.json
  def create
    @vinho = Vinho.new(vinho_params)

    respond_to do |format|
      if @vinho.save
        format.html { redirect_to @vinho, notice: 'Vinho was successfully created.' }
        format.json { render :show, status: :created, location: @vinho }
      else
        format.html { render :new }
        format.json { render json: @vinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinhos/1
  # PATCH/PUT /vinhos/1.json
  def update
    respond_to do |format|
      if @vinho.update(vinho_params)
        format.html { redirect_to @vinho, notice: 'Vinho was successfully updated.' }
        format.json { render :show, status: :ok, location: @vinho }
      else
        format.html { render :edit }
        format.json { render json: @vinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinhos/1
  # DELETE /vinhos/1.json
  def destroy
    @vinho.destroy
    respond_to do |format|
      format.html { redirect_to vinhos_url, notice: 'Vinho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vinho
      @vinho = Vinho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vinho_params
      params.require(:vinho).permit(:nome, :ano, :tipo, :foto, :descricao, :avaliacao)
    end
end

app/helpers/vinhos_helper.rb
module VinhosHelper
end

app/views/vinhos/_form.html.erb
<html lang="en">
<head>
	
</head>	
<body>


<%= form_for(@vinho, :html => { :multipart => true })  do |f| %>
  <% if @vinho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vinho.errors.count, "error") %> prohibited this vinho from being saved:</h2>

      <ul>
      <% @vinho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class=>"form-control",:placeholder=>"Nome"  %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.number_field :ano, :class=>"form-control",:placeholder=>"Ano"  %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo, :class=>"form-control",:placeholder=>"Tipo"  %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto, :class=>"form-control",:placeholder=>"Foto"  %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao, :class=>"form-control",:placeholder=>"Descricao"  %>
  </div>
  <div class="field">
    <%= f.label :avaliacao %><br>
    <%= f.text_field :avaliacao, :class=>"form-control",:placeholder=>"Avaliacao"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</body>
</html>

app/views/vinhos/edit.html.erb
<div class="container"
<h1>Editando Vinho</h1>

<%= render 'form' %>
<div class="form-group">
  <div class="col-xs-offset-3 col-xs-9">

<%= link_to 'Show', @vinho %> |
<%= link_to vinhos_path,:class =>"btn btn-info" do%>
   <i class="glyphicon glyphicon-circle-arrow-right">Back</i>
<% end %>
</div>
</div>
</div>

app/views/vinhos/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listando Vinhos...</h1>

<div class="panel-body">
   <div class="col-md-6">
        <div class="input-group h2">
            <input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisar Itens">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                     <i class="fa fa-cog fa-spin"></i>
                </button>
            </span>
        </div>
    </div>
  
   <div class="col-md-3">
        <a href="add.html" class="btn btn-primary pull-right 		h2"><i class="fa fa-user-plus"></i>Novo Item</a>
   </div>
   <table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ano</th>
      <th>Tipo</th>
      <th>Foto</th>
      <th>Descricao</th>
      <th>Avaliacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vinhos.each do |vinho| %>
      <tr>
        <td><%= vinho.nome %></td>
        <td><%= vinho.ano %></td>
        <td><%= vinho.tipo %></td>
        <td><%= vinho.foto %></td>
        <td><%= vinho.descricao %></td>
        <td><%= vinho.avaliacao %></td>
           
        <td><%= link_to 'Visualizar', vinho, :class =>"btn btn-success btn-xs" %></td>
		<td><%= link_to 'Editar', edit_vinho_path(vinho),:class =>"btn btn-warning btn-xs" %></td>
		<td><%= link_to 'Excluir', vinho, method: :delete, data: { confirm: 'Are you sure?' },:class =>"btn btn-danger btn-xs" %></td>
	      </tr>
	   <% end %>  
           
	  </tbody>
          
    </table>
    <%= paginate @vinhos %>
    

<%= link_to 'New Vinho', new_vinho_path %>

app/views/vinhos/new.html.erb
<h1>New Vinho</h1>

<%= render 'form' %>

<%= link_to 'Back', vinhos_path %>

app/views/vinhos/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @vinho.nome %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @vinho.ano %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @vinho.tipo %>
</p>

<p>
  <strong>Foto:</strong>
  <%= image_tag(@vinho.foto_url, :width => 100) if @vinho.foto.present? %>
 </p>

<p>
  <strong>Descricao:</strong>
  <%= @vinho.descricao %>
</p>

<p>
  <strong>Avaliacao:</strong>
  <%= @vinho.avaliacao %>
</p>

<%= link_to 'Edit', edit_vinho_path(@vinho) %> |
<%= link_to 'Back', vinhos_path %>
</div>