config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/vinhos')
  resources :harmonizacoes
  resources :pratos
  resources :usuarios
  resources :vinhos

end

app/models/prato.rb
class Prato < ActiveRecord::Base
end

app/controllers/pratos_controller.rb
class PratosController < ApplicationController
  before_action :set_prato, only: [:show, :edit, :update, :destroy]

  # GET /pratos
  # GET /pratos.json
  def index
    #@pratos = Prato.all
    @pratos = Prato.all.page(params['page']).per(15)
  end

  # GET /pratos/1
  # GET /pratos/1.json
  def show
  end

  # GET /pratos/new
  def new
    @prato = Prato.new
  end

  # GET /pratos/1/edit
  def edit
  end

  # POST /pratos
  # POST /pratos.json
  def create
    @prato = Prato.new(prato_params)

    respond_to do |format|
      if @prato.save
        format.html { redirect_to @prato, notice: 'Prato was successfully created.' }
        format.json { render :show, status: :created, location: @prato }
      else
        format.html { render :new }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pratos/1
  # PATCH/PUT /pratos/1.json
  def update
    respond_to do |format|
      if @prato.update(prato_params)
        format.html { redirect_to @prato, notice: 'Prato was successfully updated.' }
        format.json { render :show, status: :ok, location: @prato }
      else
        format.html { render :edit }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pratos/1
  # DELETE /pratos/1.json
  def destroy
    @prato.destroy
    respond_to do |format|
      format.html { redirect_to pratos_url, notice: 'Prato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prato
      @prato = Prato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prato_params
      params.require(:prato).permit(:nome)
    end
end

app/helpers/pratos_helper.rb
module PratosHelper
end

app/views/pratos/_form.html.erb
<%= form_for(@prato) do |f| %>
  <% if @prato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prato.errors.count, "error") %> prohibited this prato from being saved:</h2>

      <ul>
      <% @prato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class=>"form-control",:placeholder=>"Nome" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pratos/edit.html.erb
<h1>Editando Prato</h1>

<%= render 'form' %>

<%= link_to 'Show', @prato %> |
<%= link_to 'Back', pratos_path %>

app/views/pratos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Pratos</h1>
<div class="panel-body">
   <div class="col-md-6">
        <div class="input-group h2">
            <input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisar Itens">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                   <i class="fa fa-cog fa-spin"></i>
                </button>
            </span>
        </div>
    </div>
  
   <div class="col-md-3">
        <a href="add.html" class="btn btn-primary pull-right 		h2"><i class="fa fa-user-plus"></i>Novo Item</a>
   </div>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pratos.each do |prato| %>
      <tr>
        <td><%= prato.nome %></td>
        <td><%= link_to 'Show', prato %></td>
        <td><%= link_to 'Edit', edit_prato_path(prato) %></td>
        <td><%= link_to 'Destroy', prato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @pratos %>
 

<%= link_to 'Novo Prato', new_prato_path %>

app/views/pratos/new.html.erb
<h1>Novo Prato</h1>

<%= render 'form' %>

<%= link_to 'Back', pratos_path %>vo

app/views/pratos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @prato.nome %>
</p>

<%= link_to 'Edit', edit_prato_path(@prato) %> |
<%= link_to 'Back', pratos_path %>