config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/vinhos')
  resources :harmonizacoes
  resources :pratos
  resources :usuarios
  resources :vinhos

end

app/controllers/harmonizacoes_controller.rb
class HarmonizacoesController < ApplicationController
  before_action :set_harmonizaco, only: [:show, :edit, :update, :destroy]

  # GET /harmonizacoes
  # GET /harmonizacoes.json
  def index
    #@harmonizacoes = Harmonizacao.all
    @harmonizacoes = Harmonizacao.all.page(params['page']).per(15)
  end

  # GET /harmonizacoes/1
  # GET /harmonizacoes/1.json
  def show
  end

  # GET /harmonizacoes/new
  def new
    @harmonizacao = Harmonizacao.new
  end

  # GET /harmonizacoes/1/edit
  def edit
  end

  # POST /harmonizacoes
  # POST /harmonizacoes.json
  def create
    @harmonizacao = Harmonizacao.new(harmonizaco_params)

    respond_to do |format|
      if @harmonizacao.save
        format.html { redirect_to @harmonizacao, notice: 'Harmonizacao was successfully created.' }
        format.json { render :show, status: :created, location: @harmonizacao }
      else
        format.html { render :new }
        format.json { render json: @harmonizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /harmonizacoes/1
  # PATCH/PUT /harmonizacoes/1.json
  def update
    respond_to do |format|
      if @harmonizacao.update(harmonizaco_params)
        format.html { redirect_to @harmonizacao, notice: 'Harmonizacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @harmonizacao }
      else
        format.html { render :edit }
        format.json { render json: @harmonizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /harmonizacoes/1
  # DELETE /harmonizacoes/1.json
  def destroy
    @harmonizacao.destroy
    respond_to do |format|
      format.html { redirect_to harmonizacoes_url, notice: 'Harmonizacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_harmonizaco
      @harmonizacao = Harmonizacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def harmonizacao_params
      params.require(:harmonizacao).permit(:vinho_id, :prato_id)
    end
end

app/helpers/harmonizacoes_helper.rb
module HarmonizacoesHelper
end

app/views/harmonizacoes/_form.html.erb
<%= form_for(@harmonizacao) do |f| %>
  <% if @harmonizacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@harmonizacao.errors.count, "error") %> prohibited this harmonizacao from being saved:</h2>

      <ul>
      <% @harmonizacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vinho_id %><br>
    <%= f.number_field :vinho_id, :class=>"form-control",:placeholder=>"Número do vinho" %>
  </div>
  <div class="field">
    <%= f.label :prato_id %><br>
    <%= f.number_field :prato_id, :class=>"form-control",:placeholder=>"Número do prato" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/harmonizacoes/edit.html.erb
<h1>Editando Harmonizações</h1>

<%= render 'form' %>

<%= link_to 'Show', @harmonizacao %> |
<%= link_to 'Back', harmonizacoes_path %>

app/views/harmonizacoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Harmonizações</h1>
<div class="panel-body">
   <div class="col-md-6">
        <div class="input-group h2">
            <input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisar Itens">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                   <i class="fa fa-cog fa-spin"></i>
                </button>
            </span>
        </div>
    </div>
  
   <div class="col-md-3">
        <a href="add.html" class="btn btn-primary pull-right 		h2"><i class="fa fa-user-plus"></i>Novo Item</a>
   </div>
<table>
  <thead>
    <tr>
      <th>Vinho</th>
      <th>Prato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @harmonizacoes.each do |harmonizaco| %>
      <tr>
        <td><%= harmonizacao.vinho_id %></td>
        <td><%= harmonizacao.prato_id %></td>
        <td><%= link_to 'Show', harmonizacao %></td>
        <td><%= link_to 'Edit', edit_harmonizacao_path(harmonizacao) %></td>
        <td><%= link_to 'Destroy', harmonizacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @harmonizacoes %>

<%= link_to 'Novo Usuário', new_usuario_path %>
<br>

<%= link_to 'New Harmonizacao', new_harmonizacao_path %>

app/views/harmonizacoes/new.html.erb
<h1>Nova Harmonização</h1>

<%= render 'form' %>

<%= link_to 'Back', harmonizacoes_path %>

app/views/harmonizacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vinho:</strong>
  <%= @harmonizacao.vinho_id, :class=>"form-control" %>
</p>

<p>
  <strong>Prato:</strong>
  <%= @harmonizacao.prato_id, :class=>"form-control" %>
</p>

<%= link_to 'Edit', edit_harmonizacao_path(@harmonizacao) %> |
<%= link_to 'Back', harmonizacoes_path %>