config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/vinhos')
  resources :harmonizacoes
  resources :pratos
  resources :usuarios
  resources :vinhos

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    #@usuarios = Usuario.all
    @usuarios = Usuario.all.page(params['page']).per(15)
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class=>"form-control",:placeholder=>"Nome" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class=>"form-control",:placeholder=>"E-mail" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editando Usuário</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listando Usuários...</h1>

<div class="panel-body">
   <div class="col-md-6">
        <div class="input-group h2">
            <input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisar Itens">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                   <i class="fa fa-cog fa-spin"></i>
                </button>
            </span>
        </div>
    </div>
  
   <div class="col-md-3">
        <a href="add.html" class="btn btn-primary pull-right 		h2"><i class="fa fa-user-plus"></i>Novo Item</a>
   </div>
   <table class="table table-striped">  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Visualizar', usuario, :class =>"btn btn-success btn-xs" %></td>
		<td><%= link_to 'Editar', edit_usuario_path(usuario),:class =>"btn btn-warning btn-xs" %></td>
		<td><%= link_to 'Excluir', usuario, method: :delete, data: { confirm: 'Are you sure?' },:class =>"btn btn-danger btn-xs" %></td>
	      </tr>
	   <% end %>  
           
	  </tbody>
          
    </table>
    <%= paginate @usuarios %>
    

<%= link_to 'Novo Usuário', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>